name: 'shlokas'


services:
  balancer:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    networks:
      - shlokas
    volumes:
      - .logs/balancer/nginx:/var/log/nginx
      - .secrets/balancer/certs:/app/shlokas-balancer/certs


networks:
  shlokas:
    name: shlokas
