name: 'shlokas'


services:
  balancer:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    networks:
      - shlokas
    volumes:
      - .logs/:/var/log/nginx
      - .data:/app/shlokas-balancer/.data


networks:
  shlokas:
    name: shlokas
