name: 'shlokas'


services:
  balancer:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 80:80
    networks:
      - shlokas
    volumes:
      - .logs:/var/log/nginx


networks:
  shlokas:
    name: shlokas
